FROM archlinux:latest

RUN pacman -Sy \
  npm usbip qt5-base qt5-webengine gcc systemd-libs pkg-config make tcp-wrappers python \
  --noconfirm

WORKDIR /opt

COPY . .
COPY ksource/usbip_common.h /usr/include/usbip/usbip_common.h

RUN npm --prefix web ci
RUN npm run --prefix web build
RUN qmake
RUN make
